
import java.util.Stack;


public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        a_estrela.setVisible(false);
        algoritmo_genetico.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempo_final = new javax.swing.JLabel();
        btn_algoritmo_genetico = new javax.swing.JButton();
        btn_a_estrela = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        algoritmo_genetico = new javax.swing.JPanel();
        tamanho_tabuleiro = new javax.swing.JTextField();
        tamanho_populacao = new javax.swing.JTextField();
        taxa_mutacao = new javax.swing.JTextField();
        evolucao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_executar_genetico = new javax.swing.JButton();
        tempo_execucao_genetico = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        a_estrela = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tamanho_tabuleiro_1 = new javax.swing.JTextField();
        btn_executar_a = new javax.swing.JButton();
        tempo_execucao_a = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        tempo_final.setText("Tempo de execução: ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_algoritmo_genetico.setText("Algoritmo Genético");
        btn_algoritmo_genetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_algoritmo_geneticoActionPerformed(evt);
            }
        });

        btn_a_estrela.setText("A*");
        btn_a_estrela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_a_estrelaActionPerformed(evt);
            }
        });

        jLabel1.setText("Escolha o algoritmo:");

        algoritmo_genetico.setBorder(javax.swing.BorderFactory.createTitledBorder("Algoritmo Genético"));

        tamanho_tabuleiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamanho_tabuleiroActionPerformed(evt);
            }
        });

        jLabel2.setText("Tamanho Tabuleiro");

        jLabel3.setText("Tamanho População");

        jLabel4.setText("Taxa de mutação");

        jLabel5.setText("Evolução");

        btn_executar_genetico.setText("Executar");
        btn_executar_genetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_executar_geneticoActionPerformed(evt);
            }
        });

        tempo_execucao_genetico.setEditable(false);

        jLabel8.setText("Tempo de execução (ms):");

        javax.swing.GroupLayout algoritmo_geneticoLayout = new javax.swing.GroupLayout(algoritmo_genetico);
        algoritmo_genetico.setLayout(algoritmo_geneticoLayout);
        algoritmo_geneticoLayout.setHorizontalGroup(
            algoritmo_geneticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(algoritmo_geneticoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(algoritmo_geneticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempo_execucao_genetico)
                    .addComponent(tamanho_tabuleiro)
                    .addComponent(tamanho_populacao)
                    .addComponent(taxa_mutacao)
                    .addComponent(evolucao)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, algoritmo_geneticoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_executar_genetico, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(algoritmo_geneticoLayout.createSequentialGroup()
                        .addGroup(algoritmo_geneticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(0, 84, Short.MAX_VALUE)))
                .addContainerGap())
        );
        algoritmo_geneticoLayout.setVerticalGroup(
            algoritmo_geneticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(algoritmo_geneticoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tamanho_tabuleiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tamanho_populacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taxa_mutacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(evolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tempo_execucao_genetico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_executar_genetico)
                .addContainerGap())
        );

        a_estrela.setBorder(javax.swing.BorderFactory.createTitledBorder("A*"));

        jLabel6.setText("Tamanho Tabuleiro");

        btn_executar_a.setText("Executar");
        btn_executar_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_executar_aActionPerformed(evt);
            }
        });

        tempo_execucao_a.setEditable(false);
        tempo_execucao_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempo_execucao_aActionPerformed(evt);
            }
        });

        jLabel7.setText("Tempo de execução (ms):");

        javax.swing.GroupLayout a_estrelaLayout = new javax.swing.GroupLayout(a_estrela);
        a_estrela.setLayout(a_estrelaLayout);
        a_estrelaLayout.setHorizontalGroup(
            a_estrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(a_estrelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(a_estrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tamanho_tabuleiro_1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, a_estrelaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_executar_a, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tempo_execucao_a)
                    .addGroup(a_estrelaLayout.createSequentialGroup()
                        .addGroup(a_estrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );
        a_estrelaLayout.setVerticalGroup(
            a_estrelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(a_estrelaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tamanho_tabuleiro_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tempo_execucao_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_executar_a)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(btn_algoritmo_genetico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_a_estrela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addComponent(a_estrela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(algoritmo_genetico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a_estrela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_algoritmo_genetico, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btn_a_estrela, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(algoritmo_genetico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_algoritmo_geneticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_algoritmo_geneticoActionPerformed
        algoritmo_genetico.setVisible(true);
    }//GEN-LAST:event_btn_algoritmo_geneticoActionPerformed

    private void tamanho_tabuleiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamanho_tabuleiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tamanho_tabuleiroActionPerformed

    private void btn_a_estrelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_a_estrelaActionPerformed
        a_estrela.setVisible(true);
    }//GEN-LAST:event_btn_a_estrelaActionPerformed

    private void btn_executar_geneticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_executar_geneticoActionPerformed
        //Tabuleiro Algoritmo Genetico
        int populacao = Integer.parseInt(this.tamanho_populacao.getText());
        int taxa_mutacao = Integer.parseInt(this.taxa_mutacao.getText());
        int evolucao = Integer.parseInt(this.evolucao.getText());
        int tabuleiro = Integer.parseInt(this.tamanho_tabuleiro.getText());
        TabuleiroInterface tabuleiroGenetico1 = new TabuleiroInterface(tabuleiro,2);
        tabuleiroGenetico1.setTitle("Algoritmo Genetico");
        
        AlgoritmoGenetico ag = new AlgoritmoGenetico(populacao, taxa_mutacao, tabuleiro);
        tabuleiroGenetico1.mostrarSolucaoAlgoritmoGenetico(ag.pegaTabuleiro());
        long start_genetico = System.currentTimeMillis();
        ag.evoluir(evolucao);
        long elapsed_genetico = System.currentTimeMillis() - start_genetico;
        tabuleiroGenetico1.mostrarSolucaoAlgoritmoGenetico(ag.pegaTabuleiro());
        
        this.tempo_execucao_genetico.setText(String.valueOf(elapsed_genetico));
    }//GEN-LAST:event_btn_executar_geneticoActionPerformed

    private void btn_executar_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_executar_aActionPerformed
        int tabuleiro = Integer.parseInt(this.tamanho_tabuleiro_1.getText());
        TabuleiroInterface tabuleiroEstrela = new TabuleiroInterface(tabuleiro,1);
        tabuleiroEstrela.setTitle("A*");
        long start_A = System.currentTimeMillis();
        No solucaoAEstrela = tabuleiroEstrela.buscaAEstrela();
        long elapsed_A = System.currentTimeMillis() - start_A;
        
        Stack<EstadoTabuleiro> passosAEstrela = new Stack();
        while(solucaoAEstrela != null) {
            passosAEstrela.push(solucaoAEstrela.getEstadoTabuleiro());
            solucaoAEstrela = solucaoAEstrela.getPai();
        }
        
        tabuleiroEstrela.mostrarSolucao(passosAEstrela);
        
        this.tempo_execucao_a.setText(String.valueOf(elapsed_A));
    }//GEN-LAST:event_btn_executar_aActionPerformed

    private void tempo_execucao_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempo_execucao_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempo_execucao_aActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel a_estrela;
    private javax.swing.JPanel algoritmo_genetico;
    private javax.swing.JButton btn_a_estrela;
    private javax.swing.JButton btn_algoritmo_genetico;
    private javax.swing.JButton btn_executar_a;
    private javax.swing.JButton btn_executar_genetico;
    private javax.swing.JTextField evolucao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tamanho_populacao;
    private javax.swing.JTextField tamanho_tabuleiro;
    private javax.swing.JTextField tamanho_tabuleiro_1;
    private javax.swing.JTextField taxa_mutacao;
    private javax.swing.JTextField tempo_execucao_a;
    private javax.swing.JTextField tempo_execucao_genetico;
    private javax.swing.JLabel tempo_final;
    // End of variables declaration//GEN-END:variables
}
