/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import AlgoritmoGenetico.AlgoritmoGenetico;
import ProgramacaoDinamica.ProgramacaoDinamica;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author nathy
 */
public class TelaInicial extends javax.swing.JFrame {

    String url;
    int capacidadeMochila;
    int quantidadeItens;
    int [] pesoItens;
    int [] valorItens;
    
    public TelaInicial() {
        this.url = "";
        initComponents();
        btnExecutar.setEnabled(false);
        outputCaminhoArq.setEditable(false);
        outputAG.setEditable(false);
        outputPD.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        outputCaminhoArq = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnExecutar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        inputTamPopulacao = new javax.swing.JTextField();
        inputTaxaMutacao = new javax.swing.JTextField();
        inputNumGeracoes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputPD = new javax.swing.JTextPane();
        txtTempoPD = new javax.swing.JLabel();
        txtTempoAG = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        outputAG = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Problema da Mochila");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Escolha um arquivo de texto");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnExecutar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnExecutar.setText("Executar Algoritmos");
        btnExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecutarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Programação dinâmica");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("Algoritmo genético");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("Parâmetros AG");

        jLabel7.setText("Tamanho População");

        jLabel8.setText("Taxa Mutação");

        jLabel9.setText("Número de gerações");

        jScrollPane1.setViewportView(outputPD);

        txtTempoPD.setText("( )");

        txtTempoAG.setText("( )");

        outputAG.setColumns(20);
        outputAG.setRows(5);
        jScrollPane3.setViewportView(outputAG);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTempoAG))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTempoPD)))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputTamPopulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(inputTaxaMutacao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74)
                                        .addComponent(inputNumGeracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(92, 92, 92)
                                        .addComponent(jLabel9)))
                                .addGap(2, 2, 2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(outputCaminhoArq)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPesquisar))
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputCaminhoArq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(11, 11, 11)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTamPopulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNumGeracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTaxaMutacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(btnExecutar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTempoAG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTempoPD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        JFileChooser janelaPesquisarArquivo = new javax.swing.JFileChooser();
        janelaPesquisarArquivo.setMultiSelectionEnabled(false);
        janelaPesquisarArquivo.setDialogTitle("Selecione a pasta");

        janelaPesquisarArquivo.setFileFilter(new FileNameExtensionFilter("TEXT FILES", "txt")); 
        janelaPesquisarArquivo.setAcceptAllFileFilterUsed(false);
        
        janelaPesquisarArquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int resposta = janelaPesquisarArquivo.showOpenDialog(janelaPesquisarArquivo);
        //este if determina o que o programa faz ao se clicar no botao abrir ou cancelar dentro do jfc
        if (resposta == 0) {
            btnExecutar.setEnabled(true);
            url = janelaPesquisarArquivo.getSelectedFile().getAbsolutePath().toString();
            outputCaminhoArq.setText(url);
        }

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecutarActionPerformed
        this.trataArquivo();
        int tamanhoPopulacao = Integer.valueOf(inputTamPopulacao.getText());
        int taxaMutacao = Integer.valueOf(inputTaxaMutacao.getText());
        int numGeracoes= Integer.valueOf(inputNumGeracoes.getText());

        AlgoritmoGenetico ag = new AlgoritmoGenetico(tamanhoPopulacao, taxaMutacao, this.pesoItens, this.valorItens, this.capacidadeMochila, this.quantidadeItens);
        long start_genetico = System.currentTimeMillis();
        ag.evoluir(numGeracoes);
        long tempo_genetico = System.currentTimeMillis() - start_genetico;
        txtTempoAG.setText("( "+String.valueOf(tempo_genetico)+" ms )");
        String[] resultado = ag.mostraResultado();
        outputAG.setText("");
        System.out.println("Algoritmo Genetico");
        for (int i = 0; i < resultado.length; i++) {
            System.out.print("["+i+"]");
            System.out.println(resultado[i]);
//            outputAG.append(resultado[i]);
//            outputAG.append("\n");;
        }
        
        ProgramacaoDinamica pd = new ProgramacaoDinamica (this.pesoItens, this.valorItens, this.capacidadeMochila, this.quantidadeItens);
        long start_dinamico = System.currentTimeMillis();
        pd.executaAlgoritmo();
        long tempo_dinamico = System.currentTimeMillis() - start_dinamico;
        System.out.println("\nProgramção dinamica: ");
        System.out.println(pd.mostraResultado());
        txtTempoPD.setText("( "+String.valueOf(tempo_dinamico)+" ms )");
//        outputPD.setText(pd.mostraResultado());
        
        
    }//GEN-LAST:event_btnExecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }
    
    
    public void trataArquivo(){
//        /*
//        Ordem do arquivo:
//           -capacidade mochila
//           -quantidade de itens
//           -vetor de pessos
//           -vetor de valores
//       */
//        try {
//            FileReader arq = new FileReader(url);
//            BufferedReader lerArq = new BufferedReader(arq);
//            capacidadeMochila = Integer.parseInt(lerArq.readLine()); // lê a primeira linha
//            quantidadeItens = Integer.parseInt(lerArq.readLine()); // lê a segunda linha
//            String[] stringPesos = lerArq.readLine().split(" ");
//            String[] stringValores = lerArq.readLine().split(" ");
//            
//            pesoItens = new int[quantidadeItens];
//            valorItens = new int[quantidadeItens];
//    
//            int valor = stringValores.length;
//            for (int i = 0; i < stringValores.length; i++) {
//                pesoItens[i] = Integer.parseInt(stringPesos[i]);
//                valorItens[i] = Integer.parseInt(stringValores[i]);
//            }
//            
//            arq.close();
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IOException ex) {
//            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
//        } 
        try {
            // Le o arquivo 3
            FileReader arq = new FileReader(url);
            BufferedReader lerArq = new BufferedReader(arq);
            capacidadeMochila = Integer.parseInt(lerArq.readLine()); // lê a primeira linha
            quantidadeItens = Integer.parseInt(lerArq.readLine()); // lê a segunda linha
            
            pesoItens = new int[quantidadeItens];
            valorItens = new int[quantidadeItens];
    
     
            for (int i = 0; i < quantidadeItens; i++) {
                String linhaLida[] = lerArq.readLine().split(" ");
                valorItens[i] = Integer.parseInt(linhaLida[0]);
                pesoItens[i] = Integer.parseInt(linhaLida[1]);
               
            }
            
            arq.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExecutar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JTextField inputNumGeracoes;
    private javax.swing.JTextField inputTamPopulacao;
    private javax.swing.JTextField inputTaxaMutacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea outputAG;
    private javax.swing.JTextField outputCaminhoArq;
    private javax.swing.JTextPane outputPD;
    private javax.swing.JLabel txtTempoAG;
    private javax.swing.JLabel txtTempoPD;
    // End of variables declaration//GEN-END:variables
}
